name: netcdf
channels:
  - conda-forge
dependencies:
  - aiohttp
  - bottleneck
  - dask
  - gcsfs
  - h5netcdf
  - ipykernel
  - joblib
  - jupyterlab
  - matplotlib
  - nbformat
  - netcdf4
  - pandas
  - plotly
  - python
  - scikit-learn
  - scipy
  - xarray
  - xskillscore
  - zarr
  - pip:
    - -e .